[core]
context_menu = ["slouch", "pipe"]
link_opener  = ["pdetach", "xdg-open"]
maxage       = "10m"
maxpopupage  = "6s"

[bindings]
mouse_filter     = "1"
mouse_close_one  = "3"
kbd_close_latest = "Mod1-Shift-Space"
kbd_show_all     = "Mod1-Space"

[style]
#font_bold    = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
#font_regular = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
font_bold    = "/usr/share/fonts/truetype/iosevka/iosevka-bold.ttf"
font_regular = "/usr/share/fonts/truetype/iosevka/iosevka-medium.ttf"
width        = 300
x_offset     = 1590
y_offset     = 25
font_size    = 15
border_width = 2
border_color = "#FFFFFF"
padding      = 10
fg           = "#FFFFFF"
critical_bg  = "#661100"
normal_bg    = "#00665C"
low_bg       = "#333333"
