[core]
context_menu = ["slouch", "pipe"]
link_opener  = ["pdetach", "xdg-open"]
maxage       = "10m"
maxpopupage  = "5s"
max          = 5

[bindings]
mse_filter    = "1"
mse_close_one = "3"
kbd_close_top = "Mod1-Shift-Space"
kbd_show_all  = "Mod1-Space"

[style]
font_bold    = "/usr/share/fonts/truetype/hack/Hack-Bold.ttf"
font_regular = "/usr/share/fonts/truetype/hack/Hack-Regular.ttf"
width        = 300
x_offset     = 1590
y_offset     = 25
font_size    = 14
border_width = 2
border_color = "#FFFFFF"
padding      = 10
fg           = "#FFFFFF"
critical_bg  = "#771100"
normal_bg    = "#00795B"
low_bg       = "#222222"
