[core]
context_menu = ["slouch", "pipe"]
link_opener  = ["pdetach", "xdg-open"]
maxpopupage  = "7s"
max          = 100

[bindings]
mse_filter    = "1"
mse_close_one = "3"
kbd_close_top = "Mod1-Shift-Space"
kbd_show_all  = "Mod1-Space"

[style]
font_fallback = "_font/unifont-12.0.01.ttf"
font_bold    = "/home/eeojun/.local/share/fonts/Inconsolata-Bold.ttf"
font_regular = "/home/eeojun/.local/share/fonts/Inconsolata-Regular.ttf"
width        = 315
x_offset     = 1580
y_offset     = 30
font_size    = 16
border_width = 1
border_color = "#CCCCCC"
padding      = 6
fg           = "#EEEEEE"
critical_bg  = "#771100"
normal_bg    = "#225739"
low_bg       = "#121212"
