[core]
context_menu = ["slouch", "pipe"]
link_opener  = ["pdetach", "xdg-open"]
maxage       = "10m"
maxpopupage  = "5s"
max          = 100

[bindings]
mse_filter    = "1"
mse_close_one = "3"
kbd_close_top = "Mod1-Shift-Space"
kbd_show_all  = "Mod1-Space"

[style]
font_bold    = "_font/unifont-12.0.01.ttf"
font_regular = "_font/unifont-12.0.01.ttf"
width        = 300
x_offset     = 1590
y_offset     = 25
font_size    = 16
border_width = 2
border_color = "#CCCCCC"
padding      = 10
fg           = "#EEEEEE"
critical_bg  = "#771100"
normal_bg    = "#00795B"
low_bg       = "#222222"
